name: pioupiou
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - setuptools
  - twine
  - coverage
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - wrapt
  - pip:
    - mkdocs
    - mkdocs-material