site_name: Pioupiou

docs_dir: mkdocs

site_dir: docs

pages:
  - Overview: index.md
  - Tests: tests.md

theme:
  name: material

# plugins:
#   - search
#   - git-revision-date

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences

repo_name: "pioupiou"
repo_url: "https://github.com/boisgera/pioupiou"
edit_uri: edit/master/mkdocs/


