site_name: Pioupiou

docs_dir: mkdocs

site_dir: docs

nav:
  - Overview: index.md
  - Examples:
    - Height: height.md
  - Tests: tests.md

theme:
  name: material
  features:
    - navigation.expand
  icon:
    logo: material/bird
  favicon: images/favicon.png

plugins:
  - git-revision-date
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences

repo_name: "pioupiou"
repo_url: "https://github.com/boisgera/pioupiou"
edit_uri: edit/master/mkdocs/


