site_name: Pioupiou

docs_dir: mkdocs

site_dir: docs

nav:
  - Overview: index.md
  - Examples:
    - Height: height.md
    - Gaussians: gaussians.md
    - Volatility: volatility.md
  - Tests: tests.md

theme:
  name: material
  features:
    - navigation.expand
  icon:
    logo: material/bird
  favicon: images/bird.svg

plugins:
  - git-revision-date
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true 

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_name: "pioupiou"
repo_url: "https://github.com/boisgera/pioupiou"
edit_uri: edit/master/mkdocs/


