name: build
on: [push]

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]
    defaults:
      run:
        shell: bash -l {0} 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Activate Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pioupiou
          environment-file: environment.yml

      - name: Install pioupiou
        run: pip install .

      - name: Test pioupiou
        run: python test.py -v

      - name: Build the images
        run: cd mkdocs/images && ./build.py

      - name: Create coverage report
        if: matrix.os == 'ubuntu-20.04'
        run: coverage run test.py && coverage html && cp -rf htmlcov mkdocs/.

      - name: Compute coverage percentage
        if: matrix.os == 'ubuntu-20.04'
        run: echo "COVERAGE=`./coverage.sh`" >> $GITHUB_ENV

      - name: Create coverage badge
        if: matrix.os == 'ubuntu-20.04'
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 13615cd4d2f090624f8fa068f29d67f9
          filename: test.json
          label: coverage
          message: ${{ env.COVERAGE }}
          color: blue

      - name: Build documentation
        run: mkdocs build

      - name: Prepare deployment
        run: rm .gitignore

      - name: Deploy documentations
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: "docs"
          SINGLE_COMMIT: true
          PRESERVE: true