name: docs
on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0} 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Activate Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pioupiou
          environment-file: environment.yml

      - name: Build documentation
        run: mkdocs build

      - name: Prepare deployment
        run: rm .gitignore

      - name: Deploy documentations
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: "docs"
          SINGLE_COMMIT: true
          PRESERVE: true