name: test
on: [push]

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]
    defaults:
      run:
        shell: bash -l {0} 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Activate Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pioupiou
          environment-file: environment.yml

      - name: Install pioupiou
        run: pip install .

      - name: Test pioupiou
        run: python test.py -v

      - name: Compute coverage
        run: echo "COVERAGE=`./coverage.sh`"" >> $GITHUB_ENV

      - name: Create coverage badge
        if: matrix.os == 'ubuntu-20.04'
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 13615cd4d2f090624f8fa068f29d67f9
          filename: test.json
          label: Hello
          message: ${{ env.COVERAGE }}
          color: orange